# fly.toml app configuration file generated for wws-api on 2023-09-14T11:25:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wws-api"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
